# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 16:56
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.CharField(default='', max_length=20, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u7b14\u8bb0\u5185\u5bb9'),
        ),
    ]
