# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170219_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='\u662f\u4e0d\u662f\u79c1\u5bc6\u7b14\u8bb0'),
        ),
    ]
