# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='is_private',
        ),
        migrations.AddField(
            model_name='notes',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00'),
        ),
    ]
