# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotes',
            options={'verbose_name': '\u7528\u6237\u7684\u7b14\u8bb0', 'verbose_name_plural': '\u7528\u6237\u7684\u7b14\u8bb0'},
        ),
        migrations.RenameField(
            model_name='usernotes',
            old_name='course',
            new_name='note',
        ),
    ]
