# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
